
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
  

development:
  <<: *default
  database: bitnotes_development
 
test:
  <<: *default
  database: bitnotes_test

production:
  <<: *default
  database: bitnotes_production
  host: localhost
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
