# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8644f505e4f465185d29b698828b01007a40da48fa9befd4d97e480da614b1efadb14d84b028053d240a5d67e3bc547efae8ae8f9e1358be32d105282491b6b8

test:
  secret_key_base: 9b00b69afc527827a967f7141e5f5b47797a0a0f2792bc38b8fddf416b4628336a1a18d410a1a67888177adde35ac8abe21e43a6d27ea5e3126f3d26c0d9346f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
